version: '3.8'

services:
  pharma-frontend:
    volumes:
      - ./.env:/home/node/app/.env
  pharma-backend:
    build:
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:9229:9229'
    volumes:
      - ./pharma-backend:/home/node/app
      - /home/node/app/node_modules
  pharma-proxy:
    ports:
      - '127.0.0.1:80:80'
    command:
      - sh
      - -c
      - |
        nginx-debug -g 'daemon off;'
    volumes:
      - ./pharma-proxy/nginx.conf:/etc/nginx/nginx.conf
    environment:
      TZ: ${PHARMA_TIMEZONE}
    networks:
      default:
        aliases:
          - auth.pharma.test
          - pharma.test
  keycloak:
    volumes:
      - ./etc/keycloak/quarkus.local.properties:/opt/keycloak/conf/quarkus.properties
#  pharma-load-realm-sidecar:
#    image: pharma/pharma-load-realm-sidecar:latest
#    container_name: pharma_load_realm_sidecar
#    build:
#      context: pharma-load-realm-sidecar
#      dockerfile: Dockerfile
#    depends_on:
#      - keycloak
#      - pharma-proxy
#    environment:
#      PHARMA_BACKEND_CLIENT_ID: ${PHARMA_BACKEND_CLIENT_ID}
#      PHARMA_KEYCLOAK_URL: ${PHARMA_KEYCLOAK_URL}
#      PHARMA_KEYCLOAK_REALM: ${PHARMA_KEYCLOAK_REALM}
#      PHARMA_CAMUNDA_CLIENT_ID: ${PHARMA_CAMUNDA_CLIENT_ID}
#      PHARMA_KEYCLOAK_USER: ${PHARMA_KEYCLOAK_USER}
#      PHARMA_KEYCLOAK_PASSWORD: ${PHARMA_KEYCLOAK_PASSWORD}
#  pharma-load-data-sidecar:
#    image: pharma/pharma-load-data-sidecar:latest
#    container_name: PHARMA_load_data_sidecar
#    build:
#      context: pharma-load-data-sidecar
#      dockerfile: Dockerfile
#    depends_on:
#      - keycloak
#      - pharma-bpmn
#      - pharma-backend
#      - pharma-proxy
#    environment:
#      PHARMA_BACKEND_CLIENT_ID: ${PHARMA_BACKEND_CLIENT_ID}
#      PHARMA_BACKEND_CLIENT_SECRET: ${PHARMA_BACKEND_CLIENT_SECRET}
#      PHARMA_KEYCLOAK_URL: ${PHARMA_KEYCLOAK_URL}
#      PHARMA_KEYCLOAK_REALM: ${PHARMA_KEYCLOAK_REALM}
#      PHARMA_CAMUNDA_CLIENT_ID: ${PHARMA_CAMUNDA_CLIENT_ID}
#      PHARMA_CAMUNDA_CLIENT_SECRET: ${PHARMA_CAMUNDA_CLIENT_SECRET}
#      PHARMA_KEYCLOAK_USER: ${PHARMA_KEYCLOAK_USER}
#      PHARMA_KEYCLOAK_PASSWORD: ${PHARMA_KEYCLOAK_PASSWORD}


