FROM node:16-buster

# include some dev tools
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    net-tools \
    dnsutils \
    htop \
    mc \
    vim \
    && rm -rf /var/lib/apt/lists/*

USER node

RUN mkdir /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package.json ./
COPY --chown=node:node package-lock.json ./

RUN npm ci --legacy-peer-deps

COPY --chown=node:node . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
